name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  #
  # Build and test
  #
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Build
        run: |
          npm ci
          npm run build
          npm run test
      - name: Create test summary
        uses: ./
        with:
          paths: test/results/*.xml
          output: test/results/results.html
      - name: Upload test summary
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: test/results/results.html

